### ISSUE TITLE
Unable to determine language of PO file

### ISSUE THREAD

**Issue by fdalex** [wvdongen/CakePHP-I18nJs#2]
Hi.
I've been using your plugin for a long time and all is working great until now that i've updated the plugin.
When I want to create JS file, i'm doing : 
Console\cake i18n_js create_js

I have the following message : 
Unable to determine language of PO file : .../Locale/fra/LC_MESSAGES/i18n_js.fra.po

I've found the problem in the CreateJsTask.php file

```
if (preg_match('%Locale/(.*?)/LC_MESSAGES%', $file->path, $regs)) {
    $language = $regs[1];
}
else { ... }
```

I'm on a Windows server, and $file->path equals to "...\Locale\fra\LC_MESSAGES\i18n_js.fra.po"
The preg_match cannot find "fra" because it's using / instead of \ (which probably work on UNIX system i guess).

I did this change to correct the problem : 
```
if (preg_match('%Locale/(.*?)/LC_MESSAGES%', str_replace('\\', '/', $file->path), $regs)) {
    $language = $regs[1];
}
```

It's probably not the best but on a Windows server it's working. I think you should check this case.

Using CakePHP 2.9.0

**Comment by wvdongen** [comment]
I've pushed a fix: https://github.com/wvdongen/CakePHP-I18nJs/commit/e798131b055c2b3e70fb1a047bce2827fe29ce71

Let me know if it works.

**Comment by fdalex** [comment]
Hi !
Tested, no more error with your fix ;)
